# Generated by Django 3.0.6 on 2020-06-02 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojafeira', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='is_promo',
            field=models.BooleanField(default=False),
        ),
    ]
