# Generated by Django 3.0.5 on 2020-04-17 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lojafeira', '0002_feirante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feirante',
            name='cnpj',
        ),
        migrations.RemoveField(
            model_name='feirante',
            name='tipo_pessoa',
        ),
    ]
