# Generated by Django 3.0.5 on 2020-04-24 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojafeira', '0003_auto_20200417_0113'),
    ]

    operations = [
        migrations.AddField(
            model_name='feirante',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feirante',
            name='foto',
            field=models.ImageField(null=True, upload_to='fotos/'),
        ),
    ]
