# Generated by Django 3.0.5 on 2020-05-08 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojafeira', '0003_auto_20200508_0321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='descricao',
            field=models.CharField(max_length=100),
        ),
    ]
