# Generated by Django 3.0.5 on 2020-05-01 00:26

from django.db import migrations



class Migration(migrations.Migration):

    dependencies = [
        ('lojafeira', '0004_auto_20200424_0050'),
    ]

    operations = [
    ]
