# Generated by Django 3.0.5 on 2020-05-01 00:36

from django.db import migrations


def separar_nome_sobrenome(apps, schema_editor):
    Usuario = apps.get_model('lojafeira', 'Usuario')
    for usuario in Usuario.objects.all():
        if " " in usuario.nome:
            nome, sobrenome = usuario.nome.split(" ", 1)
            usuario.nome = nome
            usuario.sobrenome = sobrenome
            usuario.save()
        else:
            usuario.sobrenome = " "
            usuario.save()


class Migration(migrations.Migration):

    dependencies = [
        ('lojafeira', '0006_usuario_sobrenome'),
    ]

    operations = [
        migrations.RunPython(separar_nome_sobrenome),
    ]
